
matrix:
  include:
    - language: node_js
      before_install: cd client
      os: osx

      node_js:
        - 8
        - 6
        
      script:
        - npm build

      cache:
        yarn: true
        directories:
          - node_modules

    - sudo: false

      addons:
        apt:
          packages:
            - libgmp-dev

      # Caching so the next build will be fast too.
      cache:
        directories:
        - $HOME/.stack

      before_install:
        - cd server
        # Download and unpack the stack executable
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

      script:
        - stack setup && stack --no-terminal --skip-ghc-check test
