version: "3.3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:5.0-rc4-alpine
    ports:
      - "6379:6379"
    volumes:
      - /srv/docker/redis:/var/lib/redis
    restart: on-failure

volumes:
  data: {}
