name:                auction-server
version:             0.1.0.0
github:              "githubuser/auction-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/auction-server#readme>

dependencies:
- base >= 4.7 && < 5
- text
- websockets
- aeson
- bytestring
- containers
- directory
- process
- time
- regex-pcre
- pretty-simple
- errors
- mtl
- shared
- fae

default-extensions:
  -  BangPatterns
  -  ConstraintKinds
  -  DefaultSignatures
  -  DeriveGeneric
  -  ExistentialQuantification
  -  FlexibleContexts
  -  FlexibleInstances
  -  FunctionalDependencies
  -  GeneralizedNewtypeDeriving
  -  LambdaCase
  -  MultiParamTypeClasses
  -  MultiWayIf
  -  NamedFieldPuns
  -  OverloadedStrings
  -  PatternGuards
  -  RankNTypes
  -  RecordWildCards
  -  ScopedTypeVariables
  -  StandaloneDeriving
  -  TupleSections
  -  TypeApplications
  -  TypeFamilies
  -  TypeFamilyDependencies
  -  TypeOperators

library:
  source-dirs: src
  other-modules:
    PostTX.Incoming.Types
    PostTX.Outgoing.FormatTX
    PostTX.Outgoing.PostTX
    PostTX.Outgoing.Types
    PostTX.Types

executables:
  auction-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auction-server

tests:
  auction-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auction-server
