name:                shared
version:             0.1.0.0
github:              "githubuser/shared"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/shared#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- base16-bytestring
- aeson
- cereal
- cryptonite >= 0.24
- exceptions
- deepseq
- time
- template-haskell
- containers
- lens
- pretty
- memory
- mtl
- text
- vector

default-extensions:
  -  BangPatterns
  -  ConstraintKinds
  -  DefaultSignatures
  -  DeriveGeneric
  -  ExistentialQuantification
  -  FlexibleContexts
  -  FlexibleInstances
  -  FunctionalDependencies
  -  GeneralizedNewtypeDeriving
  -  LambdaCase
  -  MultiParamTypeClasses
  -  MultiWayIf
  -  NamedFieldPuns
  -  OverloadedStrings
  -  PatternGuards
  -  RankNTypes
  -  RecordWildCards
  -  ScopedTypeVariables
  -  StandaloneDeriving
  -  TupleSections
  -  TypeApplications
  -  TypeFamilies
  -  TypeFamilyDependencies
  -  TypeOperators


library:
  source-dirs: src
  exposed-modules:
     - SharedTypes
     - FaeTXSummary
     - FaeCrypto
     - FaeFrontend

tests:
  shared-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shared
